# Translation of todo.cfg in a more usable format

[general]
default_action = 'ls'
date_on_add = true

[colors]
done = 198
project = 154
context = 215

# Colors from original todo.cfg
# pink = '\033[38;5;211m'
# orange = '\033[38;5;203m'
# skyblue = '\033[38;5;111m'
# mediumgrey = '\033[38;5;246m'
# lavender = '\033[38;5;183m'
# tan = '\033[38;5;179m'
# forest = '\033[38;5;22m'
# maroon = '\033[38;5;52m'
# hotpink = '\033[38;5;198m'
# mintgreen = '\033[38;5;121m'
# lightorange = '\033[38;5;215m'
# lightred = '\033[38;5;203m'
# jade = '\033[38;5;35m'
# lime = '\033[38;5;154m'

# Styles
# Fields available based on rust `termcolor` crate
# Ex:
# ```
# [[styles]]
# name = 'project'
# color_fg = 154
# color_bg = 0
# bold = false
# intense = false
# underline = false
# ```
[[styles]]
name = 'done'
color_fg = 198

[[styles]]
name = 'project'
color_fg = 154

[[styles]]
name = 'context'
color_fg = 215

[[styles]]
name = 'pri_a'
color_fg = 198

[[styles]]
name = 'pri_b'
color_fg = 2

[[styles]]
name = 'pri_c'
color_fg = 4
bold = true

[[styles]]
name = 'pri_d'
color_fg = 37
bold = true

[[styles]]
name = 'pri_e'
color_fg = 179
