# Translation of todo.cfg in a more usable format

[general]
default_action = 'ls'
date_on_add = true

[colors]
done = 198
project = 154
context = 215

# [colors.fg]
# pink = '\033[38;5;211m'
# orange = '\033[38;5;203m'
# skyblue = '\033[38;5;111m'
# mediumgrey = '\033[38;5;246m'
# lavender = '\033[38;5;183m'
# tan = '\033[38;5;179m'
# forest = '\033[38;5;22m'
# maroon = '\033[38;5;52m'
# hotpink = '\033[38;5;198m'
# mintgreen = '\033[38;5;121m'
# lightorange = '\033[38;5;215m'
# lightred = '\033[38;5;203m'
# jade = '\033[38;5;35m'
# lime = '\033[38;5;154m'
#
[colors.priority]
# Color definition for priority
A = 198
B = 2
C = 4
D = 37
X = 179

#
# # Color unless explicitly defined
# X = 'tan'
