# Translation of todo.cfg in a more usable format
[general]
# File locations
todo_file = '$HOME/git/todors/src/todo.txt'
done_file = '$HOME/git/todors/src/done.txt'

default_action = 'ls'
date_on_add = true

# Styles
#
# Fields available based on rust `termcolor` crate
# Ex:
# ```
# [[styles]]
# name = 'project'
# color_fg = 154
# color_bg = 0
# bold = false
# intense = false
# underline = false
# ```
[[styles]]
name = 'done'
color_fg = 198

[[styles]]
name = 'project'
color_fg = 154

[[styles]]
name = 'context'
color_fg = 215

[[styles]]
name = 'pri_a'
color_fg = 198

[[styles]]
name = 'pri_b'
color_fg = 2

[[styles]]
name = 'pri_c'
color_fg = 4
bold = true

[[styles]]
name = 'pri_d'
color_fg = 37
bold = true

[[styles]]
name = 'pri_e'
color_fg = 179
